### ISSUE TITLE
Exception at listen

### ISSUE THREAD

**Issue by Roflord** [baykovr/AVPI#11]
Here's to hoping that this'll help development
Error occurs right after I click "Listen" after presetting a profile with a pair of test commands to try on notepad

here's the exception text:

```
************** Exception Text **************
System.ArgumentException: No recognizer of the required ID found.
Parameter name: culture
   at System.Speech.Recognition.SpeechRecognitionEngine..ctor(CultureInfo culture)
   at GAVPI.VI.load_listen(ListView statusContainer)
   at GAVPI.frmGAVPI.btnMainListen_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34014 built by: FX45W81RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
GAVPI
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Roflord/Desktop/GAVPI/GAVPI.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34239 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
InputManager
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Roflord/Desktop/GAVPI/InputManager.DLL
----------------------------------------
System.Speech
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Speech/v4.0_4.0.0.0__31bf3856ad364e35/System.Speech.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34230 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
```

And here's the contents of the profile's xml file if it helps

```
<?xml version="1.0" encoding="utf-8"?>
<gavpi>
  <VI_Action_Sequence name="20% thrust" type="VI_Action_Sequence" comment="">
    <Action type="KeyDown" value="W" />
    <Action type="Speak" value="Thrust at twenty percent" />
  </VI_Action_Sequence>
  <VI_Action_Sequence name="0% thrust" type="VI_Action_Sequence" comment="">
    <Action type="KeyDown" value="S" />
    <Action type="Speak" value="Nullifying thrust" />
  </VI_Action_Sequence>
  <VI_Trigger name="test thrust twenty percent" value="test thrust twenty percent" type="VI_Phrase" comment="">
    <VI_TriggerEvent name="20% thrust" type="VI_Action_Sequence" value="none" comment="" />
  </VI_Trigger>
  <VI_Trigger name="test thrust zero" value="test thrust zero" type="VI_Phrase" comment="">
    <VI_TriggerEvent name="0% thrust" type="VI_Action_Sequence" value="none" comment="" />
  </VI_Trigger>
</gavpi>
```

**Comment by Anarquico** [comment]
so i got the same problem every time i click listen button that exception pop up so i find out the solution that works for me i had multiple languages packs installed and by default the program start in EN US but i find out the language that was active was the EN GB u just need to go to settings and change for the right language that is active in your operating system
hope it helps

**Comment by baykovr** [comment]
Fixed. Internal dictionary localization was not matching synthesizer localization.
